theme: minima
title: My Title
author: Giacomo
email: gbucc1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  My description

# social links
twitter_username: atgiacomo # DO NOT include the @ character, or else the build will fail!
github_username:  gbucc1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
